point_cloud_path:
reference_path:

images:
  image_dir:
  image_width:
  image_height:
  vertical_offset:
  read_all:

predictor:
  type: memory
  predictions_path:

algorithm:
  compute_closest:
  voting_images:
  drop_first:
  batch_size:

projection:
  precompute:
  vectorized:
